service: trigger-dynamo

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: Viking
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:ListStreams
        - dynamodb:DescribeStreams
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    VikingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

functions:
  viking-insert:
    handler: handler.vikingsInsert
    events:
      - http:
          path: vikings
          method: post
          cors: true
  
  viking-trigger:
    handler: handler.vikingTrigger
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - VikingsTable
              - StreamArn
              

